# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: wiz-variable-group

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'


# - task: wiz@0
#   inputs:
#     command: 'image'
#     clientid: $(WIZ_CLIENT_ID)
#     secret: $(WIZ_CLIENT_SECRET)
#     image: 'golang:latest'
#     policyHitsOnly: true
#     driver: 'mountWithLayers'

- task: wiz@0
  inputs:
     command: 'image'
     clientid: $(WIZ_CLIENT_ID)
     secret: $(WIZ_CLIENT_SECRET)
     succeedOnFailures: false
     policyHitsOnly: true
     scanTags: 'cicd=ado,build=56,golang'
     image: 'golang:latest'
     scanPolicies: 'vuln-one-critical, vuln-two-high'
     scanSecrets: false
     driver: 'mountWithLayers'
     sudo: true
